UI gen
thiryr/tweetoscope pull request #22
Opened 2022-04-13 14:10 UTC by madessy

nouvelle searchbar, couleurs, transfo du dropdown en twitterlogger, correction du logo.

Tout les changements sont dans /client/src/container/NavBar/ 
Le fichier TwitterLogger a été supprimer car intégré dans le fichier DropdownMenu (de nouveau dans le dossier NavBar/Components)

2022-04-14 12:33 UTC, alixdecr submitted a review, later dismissed
Ok, need to resolve conflicts.

2022-04-17 21:55 UTC, thiryr requested changes
Does not compile on my end, found some issues. (see comments)

2022-04-17 21:55 UTC, thiryr commented on client/src/App.tsx
> +import { BaseContainer, NavContainer, TlContainer, WglContainer, WgrContainer } from "./baseStyle";
Remove WgrContainer?

2022-04-17 21:55 UTC, thiryr commented on client/src/App.tsx
> +      <WgrContainer>
Wgr -> Wgl?  Or  add Wgr.

2022-04-17 21:55 UTC, thiryr commented on client/src/containers/NavBar/NavBar.tsx
> +    const filteredPosts = filterPosts(posts, searchQuery);
filterPosts not in scope. Add it? Found implementation in SearchBar.tsx

2022-05-03 15:02 UTC, merged